quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/web_bds
quarkus.hibernate-orm.database.generation=drop-and-create


quarkus.http.port=8080

## JWT
#mp.jwt.verify.publickey.location=publicKey.pem
#mp.jwt.verify.issuer=your-issuer
#quarkus.smallrye-jwt.sign.key-location=privateKey.pem

# AWS S3
aws.region=ap-southeast-1
aws.s3.bucket=web-bds-image